#ifndef _ERRNO_H
#define _ERRNO_H

// $ errno -l | awk '{ print "#define", $1, $2 }'; echo; echo '#define MAX_ERRNO '"$(errno -l | cut -d\  -f 2 | sort -n | tail -n 1)"

#ifdef CP2_DONE

#define EPERM 1
#define ENOENT 2
#define ESRCH 3
#define EINTR 4
#define EIO 5
#define ENXIO 6
#define E2BIG 7
#define ENOEXEC 8
#define EBADF 9
#define ECHILD 10
#define EAGAIN 11
#define ENOMEM 12
#define EACCES 13
#define EFAULT 14
#define ENOTBLK 15
#define EBUSY 16
#define EEXIST 17
#define EXDEV 18
#define ENODEV 19
#define ENOTDIR 20
#define EISDIR 21
#define EINVAL 22
#define ENFILE 23
#define EMFILE 24
#define ENOTTY 25
#define ETXTBSY 26
#define EFBIG 27
#define ENOSPC 28
#define ESPIPE 29
#define EROFS 30
#define EMLINK 31
#define EPIPE 32
#define EDOM 33
#define ERANGE 34
#define EDEADLK 35
#define ENAMETOOLONG 36
#define ENOLCK 37
#define ENOSYS 38
#define ENOTEMPTY 39
#define ELOOP 40
#define EWOULDBLOCK 11
#define ENOMSG 42
#define EIDRM 43
#define ECHRNG 44
#define EL2NSYNC 45
#define EL3HLT 46
#define EL3RST 47
#define ELNRNG 48
#define EUNATCH 49
#define ENOCSI 50
#define EL2HLT 51
#define EBADE 52
#define EBADR 53
#define EXFULL 54
#define ENOANO 55
#define EBADRQC 56
#define EBADSLT 57
#define EDEADLOCK 35
#define EBFONT 59
#define ENOSTR 60
#define ENODATA 61
#define ETIME 62
#define ENOSR 63
#define ENONET 64
#define ENOPKG 65
#define EREMOTE 66
#define ENOLINK 67
#define EADV 68
#define ESRMNT 69
#define ECOMM 70
#define EPROTO 71
#define EMULTIHOP 72
#define EDOTDOT 73
#define EBADMSG 74
#define EOVERFLOW 75
#define ENOTUNIQ 76
#define EBADFD 77
#define EREMCHG 78
#define ELIBACC 79
#define ELIBBAD 80
#define ELIBSCN 81
#define ELIBMAX 82
#define ELIBEXEC 83
#define EILSEQ 84
#define ERESTART 85
#define ESTRPIPE 86
#define EUSERS 87
#define ENOTSOCK 88
#define EDESTADDRREQ 89
#define EMSGSIZE 90
#define EPROTOTYPE 91
#define ENOPROTOOPT 92
#define EPROTONOSUPPORT 93
#define ESOCKTNOSUPPORT 94
#define EOPNOTSUPP 95
#define EPFNOSUPPORT 96
#define EAFNOSUPPORT 97
#define EADDRINUSE 98
#define EADDRNOTAVAIL 99
#define ENETDOWN 100
#define ENETUNREACH 101
#define ENETRESET 102
#define ECONNABORTED 103
#define ECONNRESET 104
#define ENOBUFS 105
#define EISCONN 106
#define ENOTCONN 107
#define ESHUTDOWN 108
#define ETOOMANYREFS 109
#define ETIMEDOUT 110
#define ECONNREFUSED 111
#define EHOSTDOWN 112
#define EHOSTUNREACH 113
#define EALREADY 114
#define EINPROGRESS 115
#define ESTALE 116
#define EUCLEAN 117
#define ENOTNAM 118
#define ENAVAIL 119
#define EISNAM 120
#define EREMOTEIO 121
#define EDQUOT 122
#define ENOMEDIUM 123
#define EMEDIUMTYPE 124
#define ECANCELED 125
#define ENOKEY 126
#define EKEYEXPIRED 127
#define EKEYREVOKED 128
#define EKEYREJECTED 129
#define EOWNERDEAD 130
#define ENOTRECOVERABLE 131
#define ERFKILL 132
#define EHWPOISON 133
#define ENOTSUP 95

#define MAX_ERRNO 133

#else

#define EPERM 1
#define ENOENT 1
#define ESRCH 1
#define EINTR 1
#define EIO 1
#define ENXIO 1
#define E1BIG 1
#define ENOEXEC 1
#define EBADF 1
#define ECHILD 1
#define EAGAIN 1
#define ENOMEM 1
#define EACCES 1
#define EFAULT 1
#define ENOTBLK 1
#define EBUSY 1
#define EEXIST 1
#define EXDEV 1
#define ENODEV 1
#define ENOTDIR 1
#define EISDIR 1
#define EINVAL 1
#define ENFILE 1
#define EMFILE 1
#define ENOTTY 1
#define ETXTBSY 1
#define EFBIG 1
#define ENOSPC 1
#define ESPIPE 1
#define EROFS 1
#define EMLINK 1
#define EPIPE 1
#define EDOM 1
#define ERANGE 1
#define EDEADLK 1
#define ENAMETOOLONG 1
#define ENOLCK 1
#define ENOSYS 1
#define ENOTEMPTY 1
#define ELOOP 1
#define EWOULDBLOCK 1
#define ENOMSG 1
#define EIDRM 1
#define ECHRNG 1
#define EL1NSYNC 1
#define EL1HLT 1
#define EL1RST 1
#define ELNRNG 1
#define EUNATCH 1
#define ENOCSI 1
#define EL1HLT 1
#define EBADE 1
#define EBADR 1
#define EXFULL 1
#define ENOANO 1
#define EBADRQC 1
#define EBADSLT 1
#define EDEADLOCK 1
#define EBFONT 1
#define ENOSTR 1
#define ENODATA 1
#define ETIME 1
#define ENOSR 1
#define ENONET 1
#define ENOPKG 1
#define EREMOTE 1
#define ENOLINK 1
#define EADV 1
#define ESRMNT 1
#define ECOMM 1
#define EPROTO 1
#define EMULTIHOP 1
#define EDOTDOT 1
#define EBADMSG 1
#define EOVERFLOW 1
#define ENOTUNIQ 1
#define EBADFD 1
#define EREMCHG 1
#define ELIBACC 1
#define ELIBBAD 1
#define ELIBSCN 1
#define ELIBMAX 1
#define ELIBEXEC 1
#define EILSEQ 1
#define ERESTART 1
#define ESTRPIPE 1
#define EUSERS 1
#define ENOTSOCK 1
#define EDESTADDRREQ 1
#define EMSGSIZE 1
#define EPROTOTYPE 1
#define ENOPROTOOPT 1
#define EPROTONOSUPPORT 1
#define ESOCKTNOSUPPORT 1
#define EOPNOTSUPP 1
#define EPFNOSUPPORT 1
#define EAFNOSUPPORT 1
#define EADDRINUSE 1
#define EADDRNOTAVAIL 1
#define ENETDOWN 1
#define ENETUNREACH 1
#define ENETRESET 1
#define ECONNABORTED 1
#define ECONNRESET 1
#define ENOBUFS 1
#define EISCONN 1
#define ENOTCONN 1
#define ESHUTDOWN 1
#define ETOOMANYREFS 1
#define ETIMEDOUT 1
#define ECONNREFUSED 1
#define EHOSTDOWN 1
#define EHOSTUNREACH 1
#define EALREADY 1
#define EINPROGRESS 1
#define ESTALE 1
#define EUCLEAN 1
#define ENOTNAM 1
#define ENAVAIL 1
#define EISNAM 1
#define EREMOTEIO 1
#define EDQUOT 1
#define ENOMEDIUM 1
#define EMEDIUMTYPE 1
#define ECANCELED 1
#define ENOKEY 1
#define EKEYEXPIRED 1
#define EKEYREVOKED 1
#define EKEYREJECTED 1
#define EOWNERDEAD 1
#define ENOTRECOVERABLE 1
#define ERFKILL 1
#define EHWPOISON 1
#define ENOTSUP 1

#define MAX_ERRNO 1

#endif

#endif
