interrupt_asm.o: interrupt_asm.S interrupt.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
boot.o: boot.S multiboot.h x86_desc.h types.h abort.h
lib.o: lib.c lib.h types.h compiler.h
init.o: init.c multiboot.h types.h x86_desc.h lib.h compiler.h i8259.h \
 initcall.h abort.h debug.h tests.h
irq.o: irq.c irq.h interrupt.h types.h x86_desc.h compiler.h i8259.h \
 lib.h
exception.o: exception.c types.h interrupt.h x86_desc.h compiler.h lib.h \
 abort.h initcall.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h compiler.h
interrupt.o: interrupt.c lib.h types.h compiler.h interrupt.h x86_desc.h \
 initcall.h
keyboard.o: keyboard.c irq.h interrupt.h types.h x86_desc.h compiler.h \
 lib.h initcall.h
i8259.o: i8259.c i8259.h types.h lib.h compiler.h delay.h initcall.h
