boot.o: boot.S multiboot.h x86_desc.h types.h abort.h
interrupt_asm.o: interrupt_asm.S interrupt.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception.o: exception.c types.h interrupt.h x86_desc.h compiler.h lib.h \
  abort.h initcall.h
i8259.o: i8259.c i8259.h types.h lib.h compiler.h delay.h initcall.h
init.o: init.c multiboot.h types.h x86_desc.h lib.h compiler.h i8259.h \
  initcall.h abort.h debug.h tests.h paging.h
interrupt.o: interrupt.c lib.h types.h compiler.h interrupt.h x86_desc.h \
  initcall.h tests.h
irq.o: irq.c irq.h interrupt.h types.h x86_desc.h compiler.h i8259.h \
  lib.h
keyboard.o: keyboard.c irq.h interrupt.h types.h x86_desc.h compiler.h \
  lib.h initcall.h
lib.o: lib.c lib.h types.h compiler.h
paging.o: paging.c paging.h types.h lib.h compiler.h
rtc.o: rtc.c irq.h interrupt.h types.h x86_desc.h compiler.h lib.h \
  initcall.h rtc.h
tests.o: tests.c tests.h initcall.h types.h x86_desc.h lib.h compiler.h \
  interrupt.h
