interrupt_asm.o: interrupt_asm.S interrupt.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
boot.o: boot.S multiboot.h x86_desc.h types.h
lib.o: lib.c lib.h types.h compiler.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h compiler.h
interrupt.o: interrupt.c lib.h types.h compiler.h interrupt.h x86_desc.h
main.o: main.c multiboot.h types.h x86_desc.h lib.h compiler.h i8259.h \
 interrupt.h debug.h tests.h
i8259.o: i8259.c i8259.h types.h lib.h compiler.h
